### ISSUE TITLE
Minor issue in gofastr::q_dtm_stem

### ISSUE THREAD

**Issue by arupakaa** [trinker/gofastr#7]
Hi, Trinker!

Appreciate the awesome work! I know this isn't out there yet, but I am hoping you can address.

I've been playing with "gofastr" and love the overall execution and direction.

I, however, have been running into the following error when attempting to run q_dtm_stem()

"_Error in char_wordstem(featnames(x), language = language) : 
  whitespace detected: you can only stem tokenized texts_"

Everything runs peachily, however, when stemming isn't invoked. I tried debugging by cleaning out double spaces in my dataset (replacing "  " with " "), but received the same warning.

Any ideas here?

**Comment by trinker** [comment]
can you give me a MWE that replicates the issue?

**Comment by arupakaa** [comment]
Thanks for looking into this. I isolated on of the cases causing the error (attached). 

Here's the code:
_dt.twitter.MWE %>%
  with(gofastr::q_dtm_stem(CText, Screen.Name))_

update: I applied trim/clean from [your excellent qdap package](https://stackoverflow.com/questions/25707647/merge-multiple-spaces-to-single-space-remove-trailing-leading-spaces), but it made no difference

[dt.twitter.MWE.RData.zip](https://github.com/trinker/gofastr/files/1062625/dt.twitter.MWE.RData.zip)

**Comment by trinker** [comment]
Thank you...May I ask that you isolate the actual text that is causing the problem and supply a string in-text rather than an add on file.  I'm not trying to be difficult but I don't know you and the .RData file could contain malicious code.  Page 13 of this qdap vignette explains how to locate the problem data: https://cran.r-project.org/web/packages/qdap/vignettes/cleaning_and_debugging.pdf

**Comment by arupakaa** [comment]
Thanks. No problem at all. I identified one problematic case and have pasted below:

"Should we embrace variance, or are we destined to ️  ️ out everything that makes us unique?"

I have also included it below as a text file (/t delimited), as copy/paste can be wonky at times.

[dt.twitter.MWE.txt](https://github.com/trinker/gofastr/files/1063930/dt.twitter.MWE.txt)

Hope that helps!

**Comment by trinker** [comment]
The problem appears to be non-ascii characters in your text.  The issue occurs in the **quanteda** package and I wanted to get @kbenoit to weigh in before advising.  If it's an emergency you can strip out the non-ascii characters as I have shown in the final example here: https://github.com/kbenoit/quanteda/issues/784

**Comment by arupakaa** [comment]
Thanks for following up on this. For now, the stop-gap you suggested works beautifully. I will move ahead with this now, and will rerun things once a perm solution is available. Great stuff. Keep it up!

**Comment by trinker** [comment]
I'm going to close this I believe this has been addressed by the dev version of quanteda: https://github.com/kbenoit/quanteda/issues/796
